### ISSUE TITLE
Please help me to add a custom 'PUT' request using type script.

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [DeborahK/Angular-TypeScript#1]
Please help me to add a custom 'PUT' request using type script. 
attached is the dataAccessService.ts file screenshot from my app. 
![capture](https://cloud.githubusercontent.com/assets/16232384/12764887/98259bf2-c9c1-11e5-9c89-af726d02b0f3.PNG)

**Comment by gr4b4z** [comment]
Create ActionDescriptor.

 var updateAction : ng.resource.IActionDescriptor = {
            method: 'PUT',
            isArray: false
        };
 return <IDataAccessService> $resource('/api/emailInboxConfig/:id', { id: '@id' }, {
            update: updateAction
        });

and 
extend IDataAccessService by adding update method.
interface IDataAccessService extends ng.resource.IResourceClass<IEmail...>
{
    update(IEmployee) : IEmployee;
}

**Comment by rajeshmuraleedharan** [comment]
Thanks - it worked perfectly!. Attached is the latest code.
![capture](https://cloud.githubusercontent.com/assets/16232384/12806281/1d0e3316-caca-11e5-91b5-6e2f13d1bde9.PNG)
