### ISSUE TITLE
DEPRECATED: TSD is deprecated, please use @types

### ISSUE THREAD

**Issue by leocaseiro** [DeborahK/Angular-TypeScript#3]
Hi, I'm following your course [Angular with Typescript](https://app.pluralsight.com/library/courses/angular-typescript/table-of-contents) and at the episode [2.4.Installing TypeScript Definition Manager](https://app.pluralsight.com/player?course=angular-typescript&author=deborah-kurata&name=angular-typescript-m2&clip=4&mode=live) you are teaching to use [tsd](https://github.com/DefinitelyTyped/tsd). However, tsd is [deprecated](https://github.com/DefinitelyTyped/tsd/issues/269) as you can see in their readme, we should use [typings](https://github.com/typings/typings) instead.

I don't think it's a big issue, but that would be nice update in the course.

Thanks

**Comment by Supratentorial** [comment]
Agree with above.

**Comment by DeborahK** [comment]
I have an updated course that uses typings here: "Angular 2: Getting Started" http://bit.ly/Angular2GettingStarted

**Comment by leocaseiro** [comment]
Just an update on this. Use @types now! That's the new Declaration Types for TypeScript: https://github.com/Microsoft/TypeScript/issues/9184
